@endpoint=http://app1.console.smallsaas.cn:8001
@adminToken=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzNzA2MDA1LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTYyOTgwMDV9.nH3W8nkLMzrBp_VybRJ-ZnNjCG96RqD5a6-HikifXV9hQ618btKd8MGxoPf2XIroEzDc4Gj4JoVKk7dSBoB0zA

@A_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE4IiwidXNlcklkIjoiNiIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxMTAsImp0aSI6IjYiLCJzdWIiOiJBLTEiLCJleHAiOjE2NTYyOTgxMTB9.YN-_CKUKkWeLVnqNgfA3QHbKlI6kfr0-SK17X7akfhx25QMx-auwO8BnIDrFIqvAkOD3rZ251nWos3HrudZtow

@A_2token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE5IiwidXNlcklkIjoiNyIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0yIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxNTEsImp0aSI6IjciLCJzdWIiOiJBLTIiLCJleHAiOjE2NTYyOTgxNTF9.N_yWlEwVcqkdC6HRPskPrBYiiSW8TyL9a3uyWECmDUTVZxkUYcIXxuMUQwwgdjSdWUiIEd_Hj1Eup7LfjWs8yg

@A_1_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjIyIiwidXNlcklkIjoiOCIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xLTEiLCJ1c2VyVHlwZSI6MCwiZGV2VXNlclR5cGUiOjAsImJVc2VyVHlwZSI6IlNZU1RFTSIsImJVc2VySWQiOjAsImlhdCI6MTY1MzcwNjE3MywianRpIjoiOCIsInN1YiI6IkEtMS0xIiwiZXhwIjoxNjU2Mjk4MTczfQ.jQo-SxSEimkRJ2YqSIhsHaX7w8NQZ46J5ub8P6mYcQOFm3loYqi-dxxhtbO_-irHHvuc9sd2Zn9CrlnzXOJvmw



### 获取社区列表
GET {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies
Authorization: {{adminToken}}


### 查询id为1 的社区信息
GET {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies/9
Authorization: {{adminToken}}

###分页查询unit信息
GET {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies/?pageNum=1&pageSize=10
Authorization:{{adminToken}}



### 增添社区信息
POST {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies
Content-Type: application/json
Authorization: {{adminToken}}
{
    "community": "g社区",
    "communityCode": "6"
}

### 增添社区信息 item为子项楼栋信息
POST {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies
Content-Type: application/json
Authorization: {{adminToken}}
{
    "community": "g社区",
    "communityCode": "6",
    "items": [
      {
        "code": "e1",
        "floors": 10,
        "id": 1,
        "units": 4,
        "orgId": 18
      },
      {
        "code": "E2",
        "floors": 10,
        "id": 2,
        "units": 4,
        "orgId": 1
      },
      {
        "code": "E3",
        "floors": 11,
        "id": 3,
        "units": 5,
        "orgId": 1
      },
      {
        "code": "E4",
        "floors": 10,
        "id": 4,
        "units": 5,
        "orgId": 1
      }
    ]
}

### 更新房产信息
PUT {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies/6
Content-Type: application/json
Authorization:{{adminToken}}
{
    "community": "E社区",
    "communityCode": "2"
}



### 删除用户房产信息
DELETE {{endpoint}}/api/crud/house/housePropertyCommunity/housePropertyCommunityies/6
Authorization:{{adminToken}}