@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@adminToken =Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzNzA2MDA1LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTYyOTgwMDV9.nH3W8nkLMzrBp_VybRJ-ZnNjCG96RqD5a6-HikifXV9hQ618btKd8MGxoPf2XIroEzDc4Gj4JoVKk7dSBoB0zA

@A_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE4IiwidXNlcklkIjoiNiIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxMTAsImp0aSI6IjYiLCJzdWIiOiJBLTEiLCJleHAiOjE2NTYyOTgxMTB9.YN-_CKUKkWeLVnqNgfA3QHbKlI6kfr0-SK17X7akfhx25QMx-auwO8BnIDrFIqvAkOD3rZ251nWos3HrudZtow

@A_2token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE5IiwidXNlcklkIjoiNyIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0yIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxNTEsImp0aSI6IjciLCJzdWIiOiJBLTIiLCJleHAiOjE2NTYyOTgxNTF9.N_yWlEwVcqkdC6HRPskPrBYiiSW8TyL9a3uyWECmDUTVZxkUYcIXxuMUQwwgdjSdWUiIEd_Hj1Eup7LfjWs8yg

@A_1_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjIyIiwidXNlcklkIjoiOCIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xLTEiLCJ1c2VyVHlwZSI6MCwiZGV2VXNlclR5cGUiOjAsImJVc2VyVHlwZSI6IlNZU1RFTSIsImJVc2VySWQiOjAsImlhdCI6MTY1MzcwNjE3MywianRpIjoiOCIsInN1YiI6IkEtMS0xIiwiZXhwIjoxNjU2Mjk4MTczfQ.jQo-SxSEimkRJ2YqSIhsHaX7w8NQZ46J5ub8P6mYcQOFm3loYqi-dxxhtbO_-irHHvuc9sd2Zn9CrlnzXOJvmw

### t_house_property_building测试用例


###获取楼栋列表
GET {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings
Authorization: {{adminToken}}


### 分页查询楼栋列表
GET {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings?pageNum=1&pageSize=10
Authorization: {{adminToken}}



### 查询楼栋id为1 的详情信息
GET {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/41
Authorization: {{adminToken}}



### 增添楼栋信息
#### community、code不能为空
POST {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings
Content-Type: application/json
Authorization: {{adminToken}}

{
    "communityId":2,
    "area":"",
    "code":"B3",
    "floors":30,
    "units":5
}


### 更新楼栋id为40 的信息
PUT {{service}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/14
Content-Type: application/json
Authorization:{{adminToken}}
{
    "communityId":2,
    "area":"",
    "code":"B5",
    "floors":12,
    "units":3
}


### 更新楼栋信息，删除原来全部子项信息，添加item子项
PUT {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/41
Content-Type: application/json
Authorization:{{adminToken}}
{
    "communityId":2,
    "area":"",
    "code":"g4",
    "floors":10,
    "units":4,
    "items":[
       {
        "number": "1003",
        "unitId": 65,
        "buildingId": 41
      }
    ]
}


### 删除楼栋信息
DELETE {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/39
Authorization:{{adminToken}}