@endpoint=http://localhost:8080

@adminToken =Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzNzA2MDA1LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTYyOTgwMDV9.nH3W8nkLMzrBp_VybRJ-ZnNjCG96RqD5a6-HikifXV9hQ618btKd8MGxoPf2XIroEzDc4Gj4JoVKk7dSBoB0zA

@A_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE4IiwidXNlcklkIjoiNiIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxMTAsImp0aSI6IjYiLCJzdWIiOiJBLTEiLCJleHAiOjE2NTYyOTgxMTB9.YN-_CKUKkWeLVnqNgfA3QHbKlI6kfr0-SK17X7akfhx25QMx-auwO8BnIDrFIqvAkOD3rZ251nWos3HrudZtow

@A_2token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE5IiwidXNlcklkIjoiNyIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0yIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxNTEsImp0aSI6IjciLCJzdWIiOiJBLTIiLCJleHAiOjE2NTYyOTgxNTF9.N_yWlEwVcqkdC6HRPskPrBYiiSW8TyL9a3uyWECmDUTVZxkUYcIXxuMUQwwgdjSdWUiIEd_Hj1Eup7LfjWs8yg

@A_1_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjIyIiwidXNlcklkIjoiOCIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xLTEiLCJ1c2VyVHlwZSI6MCwiZGV2VXNlclR5cGUiOjAsImJVc2VyVHlwZSI6IlNZU1RFTSIsImJVc2VySWQiOjAsImlhdCI6MTY1MzcwNjE3MywianRpIjoiOCIsInN1YiI6IkEtMS0xIiwiZXhwIjoxNjU2Mjk4MTczfQ.jQo-SxSEimkRJ2YqSIhsHaX7w8NQZ46J5ub8P6mYcQOFm3loYqi-dxxhtbO_-irHHvuc9sd2Zn9CrlnzXOJvmw

### 主表t_house_property_building测试用例


### 增添楼栋信息
#### community、code不能为空

POST {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings
Content-Type: application/json
Authorization: {{adminToken}}
{
   "org_id":2,
    "community":"测试3社区",
    "community_code":"B333",
    "area":"",
    "code":"D2",
    "floors":10,
    "units":4,
}

### 楼栋列表
GET {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings
Authorization: {{adminToken}}

### 查询楼栋详情
GET {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/1
Authorization: {{adminToken}}

###分页查询楼栋信息
GET {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings?pageNum=1&pageSize=10
Authorization: {{adminToken}}

### 更新楼栋信息
PUT {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/2
Content-Type: application/json
Authorization:{{adminToken}}
{
    "org_id":2,
    "community":"测试4社区",
    "community_code":"B333",
    "area":"",
    "code":"D2",
    "floors":10,
    "units":4,
}


### 增加用户房产编号,同时更新楼栋信息
PUT {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/5
Content-Type: application/json
Authorization:{{adminToken}}
{
    "org_id":2,
    "community":"测试6社区",
    "community_code":"B339",
    "area":"",
    "code":"G4",
    "floors":10,
    "units":4,
    "items":[
        {
            "user_id":26,
            "number":"D223"
        },
        {
           "user_id":27,
            "number":"D221"
        }
    ]
}


### 删除楼栋信息
DELETE {{endpoint}}/api/crud/house/housePropertyBuilding/housePropertyBuildings/3
Authorization:{{adminToken}}



### 子表house_property_unit测试用例




### 增加房产信息
POST {{endpoint}}/api/crud/house/housePropertyBuildingUnit/housePropertyBuildingUnits
Content-Type: application/json
Authorization:{{adminToken}}
{
    "building_id":5,
    "number":"D221"
}


### 查询用户房产详情
GET {{endpoint}}/api/crud/house/housePropertyBuildingUnit/housePropertyBuildingUnits/1
Authorization: {{adminToken}}

###分页查询房产详情
GET {{endpoint}}/api/crud/house/housePropertyBuildingUnit/housePropertyBuildingUnits/?pageNum=1&pageSize=10
Authorization:{{adminToken}}


### 更新房产信息
PUT {{endpoint}}/api/crud/house/housePropertyBuildingUnit/housePropertyBuildingUnits/2
Content-Type: application/json
Authorization:{{adminToken}}
{
    "user_id":20,
    "building_id":5,
    "number":"D225"
}

### 初始化房屋unit
POST {{endpoint}}/api/crud/house/housePropertyBuildingUnit/housePropertyBuildingUnits/init
Authorization:{{adminToken}}


### 删除用户房产信息
DELETE {{endpoint}}/api/crud/house/housePropertyUnit/housePropertyUnits/19




###获取building
GET {{endpoint}}/api/u/house/house/housePropertyUnit

### 查询楼栋详情
GET {{endpoint}}/api/u/house/house/housePropertyUnit/1



###获得用户的装修方案
GET {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/1

### 获得用户某一装修方案的家居
GET {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?decoratePlanId=1&userId=1


### 创建装修地址
POST {{endpoint}}/api/crud/house/houseUserDecorateAddress/houseUserDecorateAddresses
Authorization:{{adminToken}}
{
    "unitId": "2",
    "userId": "1",
    "decoratePlanId": "2",
}


###查看用户装修地址
GET {{endpoint}}/api/crud/house/houseUserDecorateAddress/houseUserDecorateAddresses
Authorization:{{adminToken}}


PUT {{endpoint}}/api/crud/house/houseUserDecorateAddress/houseUserDecorateAddresses
Authorization:{{adminToken}}
{
    "userId": "1",
    "decoratePlanId": "2",
}


#### 修改用户地址
PUT {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/userDecoratePlanAddress?userId=1&decoratePlanId=2
{
    "unitId": "37"
}

### 增加用户装修计划地址
POST {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/userDecoratePlanAddress
{
    "userId": "1",
    "decoratePlanId": "2",
    "unitId": "37"
}


GET {{endpoint}}/api/crud/house/houseUserDecoratePlan/houseUserDecoratePlans
Authorization:{{adminToken}}


PUT {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?userId=1&decoratePlanId=1&funitureId=13
{
    "changedFunitureId":18
}

DELETE {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?userId=1&decoratePlanId=1&funitureId=18
{
    
}