@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@token =Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6Mjg0LCJhY2NvdW50IjoiODhiOGMwOGIwNTQ2NGFkMTgzM2UyY2RmYzA1YTk2ODMiLCJkb21haW5Vc2VySWQiOiIiLCJpYXQiOjE2NTQwNTg0ODgsImp0aSI6IjI4NCIsInN1YiI6Ijg4YjhjMDhiMDU0NjRhZDE4MzNlMmNkZmMwNWE5NjgzIiwiZXhwIjoxNjU0MzE3Njg4fQ.5FLTi7TwztrQ_WsW4OGQPOcZIkqm8ysUWDjlIJtZQVioUI6U6RWysMWNXMHOPCpd4bXeXX2gz-A1IQnB5ZulhQ



# 获取用户的装修计划列表
GET {{service}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans?pageNum=1&pageSize=10
Authorization:{{token}}

### 获取用户装修计划里面的id
GET {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?decoratePlanId=1&userId=1


### 用户替换装修计划里面的家居
PUT {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?userId=1&decoratePlanId=1&funitureId=13
{
    "changeOption": "change",
    "changedFunitureId": 18,
    "funitureNumber": 1,
    "note": "替换原因"
}


### 用户移除装修计划里面的家居
DELETE {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?userId=1&decoratePlanId=1&funitureId=18
Content-Type:application/json
{
    "changeOption": "remove",
    "note": "移除原因"
}

### 添加用户装修计划地址
POST {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/userDecoratePlanAddress
Content-Type:application/json
{
    "decoratePlanId": "2",
    "unitId": "38",
    "userId": "1"
}

### 修改用户装修计划安装地址
PUT {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/userDecoratePlanAddress?userId=1&decoratePlanId=2
{
    "unitId": "38"
}