@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@adminToken =Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzNzA2MDA1LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTYyOTgwMDV9.nH3W8nkLMzrBp_VybRJ-ZnNjCG96RqD5a6-HikifXV9hQ618btKd8MGxoPf2XIroEzDc4Gj4JoVKk7dSBoB0zA


@token =Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6MzEsInVzZXJJZCI6Mjk4LCJhY2NvdW50IjoiNTc0ZTY2N2VlODEyNDI1OTlhMzZkOWU3YzJmMGJlYWEiLCJkb21haW5Vc2VySWQiOiIiLCJpYXQiOjE2NTU3NjczNzAsImp0aSI6IjI5OCIsInN1YiI6IjU3NGU2NjdlZTgxMjQyNTk5YTM2ZDllN2MyZjBiZWFhIiwiZXhwIjoxNjU2MDI2NTcwfQ.ECNkwHD2sKsZIkyG53LY4DTTaJrB_eb0Rvt0GoK9Pwwlaw27p0V-HYNY24-W79vtqFCn2bpor3UzTYC0YTeQTA

### 获取小区
#tenantId 为社区id
GET {{service}}/api/u/asset/community
Authorization:{{token}}

### 改变或者增加用户小区状态
POST {{service}}/api/u/asset/community/userCommunityStatus?communityId=1
Authorization: {{token}}


### 获取楼栋信息
GET {{endpoint}}/api/u/asset/building
Authorization:{{token}}


### 获取房屋信息 
GET {{endpoint}}/api/u/asset/asset/{buildingId}
Authorization:{{token}}


###获取房屋详情信息
GET {{endpoint}}/api/u/asset/asset/details/{assetId}




### 获取用户的地址信息
GET {{service}}/api/u/asset/user/userAsset
Authorization:{{token}}


### 增加用户地址
POST {{endpoint}}/api/u/asset/user/userAsset
Authorization:{{token}}
{
      "asset_id": 337
}

### 修改用户安装地址
# 7为修改前assetId
PUT {{endpoint}}/api/u/asset/user/userAsset/7
Authorization:{{token}}

{
      "asset_id": 23
}

### 删除用户安装地址
# 7为主键assetId
DELETE {{endpoint}}/api/u/asset/user/userAsset/4
Authorization:{{token}}


