@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@adminToken =Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzNzA2MDA1LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTYyOTgwMDV9.nH3W8nkLMzrBp_VybRJ-ZnNjCG96RqD5a6-HikifXV9hQ618btKd8MGxoPf2XIroEzDc4Gj4JoVKk7dSBoB0zA


@token =Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6Mjg3LCJhY2NvdW50IjoiMTIyNmJjMjk2OGI0NDYwMmE2YWQ1N2UwZDY2N2JhOTUiLCJkb21haW5Vc2VySWQiOiIiLCJpYXQiOjE2NTQ4MjUxMTgsImp0aSI6IjI4NyIsInN1YiI6IjEyMjZiYzI5NjhiNDQ2MDJhNmFkNTdlMGQ2NjdiYTk1IiwiZXhwIjoxNjU1MDg0MzE4fQ.CllbeQ_mbCjaNjbkNLza6GqRnbJIc8cRUTWHL80qLvqkwua5bLbtQU5jLAyKKl-oCnGtqjVogwG-m4B5vuwvUQ

### 获取全部楼栋信息
GET {{endpoint}}/api/u/house/house/housePropertyUnit?common=false
Authorization:{{token}}


### 通过楼栋id获取整栋楼的 房屋
GET {{service}}/api/u/house/house/housePropertyUnit


### 获取用户的安装地址信息
GET {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit
Authorization:{{token}}


### 增加用户安装地址
POST {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit
Authorization:{{token}}
{
      "room_id": 303
}

### 修改用户安装地址
# 7为主键id
PUT {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit/7
Authorization:{{token}}

{
      "room_id": 23
}

### 删除用户安装地址
# 7为主键id
DELETE {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit/7
Authorization:{{token}}

### 获取社区
GET {{service}}/api/u/house/house/housePropertyUnit/community



###查询用户是否有社区状态
GET {{endpoint}}/api/u/house/house/housePropertyUnit/userCommunityStatus
Authorization:{{token}}

### 改变或者增加用户社区状态
POST {{service}}/api/u/house/house/housePropertyUnit/userCommunityStatus
Authorization:{{token}}

{
      "communityId":3
}