# @endpoint=http://localhost:8080
@endpoint=http://app1.console.smallsaas.cn:8001
@token=Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MzExLCJhY2NvdW50IjoiMDNiMzBhMjMzYzllNGFmNGI4MWQxNTE1MDdjNDQwOGIiLCJkb21haW5Vc2VySWQiOiIiLCJpYXQiOjE2NTY0NzI4MzMsImp0aSI6IjMxMSIsInN1YiI6IjAzYjMwYTIzM2M5ZTRhZjRiODFkMTUxNTA3YzQ0MDhiIiwiZXhwIjoxNjU2NzMyMDMzfQ.Y89zEBrTuOh_utVELbFcpFj-bSgVu9HFX3aHjBjBu0n1hUu2aKUoWEdj1IdYQHmbKpiQSYR2RDrstzMmgdrvkg

