@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@token =Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6Mjg0LCJhY2NvdW50IjoiODhiOGMwOGIwNTQ2NGFkMTgzM2UyY2RmYzA1YTk2ODMiLCJkb21haW5Vc2VySWQiOiIiLCJpYXQiOjE2NTQwNTg0ODgsImp0aSI6IjI4NCIsInN1YiI6Ijg4YjhjMDhiMDU0NjRhZDE4MzNlMmNkZmMwNWE5NjgzIiwiZXhwIjoxNjU0MzE3Njg4fQ.5FLTi7TwztrQ_WsW4OGQPOcZIkqm8ysUWDjlIJtZQVioUI6U6RWysMWNXMHOPCpd4bXeXX2gz-A1IQnB5ZulhQ



### 获取全部楼栋信息
GET {{endpoint}}/api/u/house/house/housePropertyUnit


### 通过楼栋id获取整栋楼的 unit
GET {{endpoint}}/api/u/house/house/housePropertyUnit/1


### 获取用户的安装地址信息
GET {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit
Authorization:{{token}}


### 增加用户安装地址
POST {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit
{
      "unitId": 45,
      "userId": "1"
}

### 修改用户安装地址
# 7为主键id
PUT {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit/7
{
      "unitId": 46,
      "userId": "1"
}
### 删除用户安装地址
# 7为主键id
DELETE {{endpoint}}/api/u/house/house/housePropertyUnit/userUnit/7


### 获取社区
GET {{service}}/api/u/house/house/housePropertyUnit/community

### 获取社区有什么房型
GET {{service}}/api/u/house/house/housePropertyUnit/houseType?communityId=2

### 获取社区房型有什么楼栋编号
GET {{service}}/api/u/house/house/housePropertyUnit/houseBuilding?houseType=三室两厅&communityId=1

####获取某社区某房型某楼栋的全部房间
GET {{service}}/api/u/house/house/housePropertyUnit/houseBuildingUnit?houseType=四室两厅&buildingId=1&communityId=1