@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@token =Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6Mjg1LCJhY2NvdW50IjoiMDAwYTY3NTcxNTM5NGJjYTk1ZmQ4OTcwOGViOTVhZDgiLCJkb21haW5Vc2VySWQiOiIiLCJpYXQiOjE2NTQ2NTg1NzcsImp0aSI6IjI4NSIsInN1YiI6IjAwMGE2NzU3MTUzOTRiY2E5NWZkODk3MDhlYjk1YWQ4IiwiZXhwIjoxNjU0OTE3Nzc3fQ.i1b1W5XaYlW3YLOLl1pfE4G2w69-qA-XZ4iUH7WF3jOf8iN6UrRTRNK3ad71Ltx7J1PbZQHtWH5XxaxfzRx8pA



# 获取用户的装修计划列表
GET {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans?pageNum=1&pageSize=10
Authorization:{{token}}

### 获取用户装修计划里面的id
GET {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?decoratePlanId=1
Authorization:{{token}}

### 用户替换装修计划里面的家居
PUT {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?userId=1&decoratePlanId=1&funitureId=16
Authorization:{{token}}
{
    "changeOption": "change",
    "changedFunitureId": 18,
    "funitureNumber": 1,
    "note": "替换原因"
}


### 用户移除装修计划里面的家居
DELETE {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/funiture?&decoratePlanId=1&funitureId=14
Authorization:{{token}}
Content-Type:application/json
{
    "changeOption": "remove",
    "note": "移除原因"
}



### 添加用户装修计划地址
POST {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/userDecoratePlanAddress
Authorization:{{token}}
Content-Type:application/json
{
    "decoratePlanId": "2",
    "unitId": "38",
}

### 修改用户装修计划安装地址
PUT {{endpoint}}/api/u/house/houseUserDecoratePlan/houseUserDecoratePlans/userDecoratePlanAddress?decoratePlanId=2
Authorization:{{token}}
{
    "unitId": "38"
}