SELECT * FROM t_house_application_intermediary;
SELECT * FROM t_house_application_operations ;
SELECT * FROM t_house_appointment WHERE address_id in(SELECT id FROM t_house_rent_asset WHERE asset_id IS NOT NULL);
SELECT * FROM t_house_asset_complaint;
SELECT * FROM t_house_asset_demand_supply ;
SELECT * FROM t_house_asset_exchange_request ;
SELECT * FROM t_house_asset_log ;
SELECT * FROM t_house_asset_match_log ;
SELECT * FROM t_house_equity_demand_supply ;
SELECT * FROM t_house_rent_asset WHERE asset_id IS NOT NULL;
SELECT * FROM t_house_subscribe WHERE subscribe_id in(SELECT id FROM t_house_rent_asset WHERE asset_id IS NOT NULL);
SELECT * FROM t_house_unlike_log;
SELECT * FROM t_house_user_address ;
SELECT * FROM t_house_user_asset ;
SELECT * FROM t_house_user_community_status ;
SELECT * FROM t_house_user_decorate_funiture ;
SELECT * FROM t_house_user_decorate_plan ;
SELECT * FROM t_house_user_note ;
SELECT * FROM t_house_user_tag;
SELECT * FROM t_house_user_tag_relate;